// Looks up an Open Library cover id for every book and writes src/data/covers.js.
// Run with: npm run covers
// Books already carrying an id are skipped, so this is cheap to re-run after
// adding titles, and safe to interrupt.

import { writeFileSync } from 'node:fs';
import { books } from '../src/data/books.js';
import { coverIds } from '../src/data/covers.js';

const OUT = new URL('../src/data/covers.js', import.meta.url);
const DELAY_MS = 700; // Open Library starts 429ing well below this.

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const covers = { ...coverIds };

const surname = (author) => author.trim().split(/\s+/).pop().toLowerCase();

const normalize = (s) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]/g, '');

async function fetchJson(url, attempt = 1) {
  const res = await fetch(url, {
    headers: { 'User-Agent': 'reading-list/0.1 (personal project)' },
  });
  if (res.status === 429 || res.status >= 500) {
    if (attempt > 4) throw new Error(`${res.status} after ${attempt} attempts`);
    const wait = DELAY_MS * 2 ** attempt;
    console.log(`    ${res.status}, backing off ${wait}ms`);
    await sleep(wait);
    return fetchJson(url, attempt + 1);
  }
  if (!res.ok) throw new Error(String(res.status));
  return res.json();
}

// Prefer a result whose author surname and title both match. Editions are often
// catalogued under a translator or a transliterated author name, so fall back to
// any result that has a cover rather than giving up.
function pickDoc(docs, book) {
  const withCover = docs.filter((d) => d.cover_i);
  if (!withCover.length) return null;

  const want = surname(book.author);
  const wantTitle = normalize(book.title);

  const byAuthor = withCover.filter((d) =>
    (d.author_name || []).some((a) => surname(a) === want)
  );
  const pool = byAuthor.length ? byAuthor : withCover;

  return (
    pool.find((d) => normalize(d.title || '') === wantTitle) ||
    pool.find((d) => normalize(d.title || '').startsWith(wantTitle)) ||
    pool[0]
  );
}

/** Emit the map as a JS module, so Node and Vite load it the same way. */
function render(map) {
  const rows = Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  '${k}': ${v === null ? 'null' : v},`)
    .join('\n');

  return `// Open Library cover ids, keyed by book id. Generated by scripts/fetch-covers.mjs
// and committed so the app never calls their API at runtime. Regenerate with
// \`npm run covers\` after adding books; existing entries are left alone.

export const coverIds = {
${rows}
};

/** size: S, M or L. Null when a book has no cover on record. */
export function coverUrl(id, size = 'M') {
  return id ? \`https://covers.openlibrary.org/b/id/\${id}-\${size}.jpg\` : null;
}
`;
}

let found = 0;
let missing = 0;
const todo = books.filter((b) => !covers[b.id]);

console.log(`${books.length} books, ${todo.length} to look up\n`);

for (const [i, book] of todo.entries()) {
  // Query title and author together and take a wide slice: a narrow
  // title+author query misses editions whose author is catalogued natively.
  const url =
    'https://openlibrary.org/search.json?' +
    new URLSearchParams({
      q: `${book.title} ${book.author}`,
      fields: 'title,author_name,cover_i',
      limit: '25',
    });

  try {
    const data = await fetchJson(url);
    const doc = pickDoc(data.docs || [], book);
    covers[book.id] = doc ? doc.cover_i : null;
    if (doc) {
      found++;
      console.log(`[${i + 1}/${todo.length}] ${book.title} -> ${doc.cover_i}`);
    } else {
      missing++;
      console.log(`[${i + 1}/${todo.length}] ${book.title} -> none`);
    }
  } catch (err) {
    missing++;
    console.log(`[${i + 1}/${todo.length}] ${book.title} -> failed: ${err.message}`);
  }

  // Write as we go so an interrupted run keeps its progress.
  writeFileSync(OUT, render(covers));
  await sleep(DELAY_MS);
}

console.log(`\ndone: ${found} found, ${missing} without a cover`);
