// Looks up a poster for every non-book item and writes src/data/posters.js.
// Run with: npm run posters
// Books have their own Open Library covers (see fetch-covers.mjs). Items that
// already have an entry are skipped, including ones set to null on purpose (a
// lookup that found the wrong thing), so this is cheap to re-run and safe to
// interrupt.
//
// Sources, none of which need a key:
//   anime, manga   AniList GraphQL
//   show           TVmaze
//   film, game, comic   Wikipedia's lead image, trying the disambiguated
//                       title first ("Soma (video game)") then a search

import { writeFileSync } from 'node:fs';
import { media } from '../src/data/media.js';
import { posters } from '../src/data/posters.js';

const OUT = new URL('../src/data/posters.js', import.meta.url);
const UA = { 'User-Agent': 'ramyan-reads/0.1 (personal project)' };
// AniList allows about 30 requests a minute.
const DELAY = { anime: 2200, manga: 2200, show: 600, film: 300, game: 300, comic: 300 };

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const found = { ...posters };

async function getJson(url, init = {}, attempt = 1) {
  const res = await fetch(url, { ...init, headers: { ...UA, ...(init.headers || {}) } });
  if (res.status === 429 || res.status >= 500) {
    if (attempt > 4) throw new Error(`${res.status} after ${attempt} attempts`);
    const wait = (Number(res.headers.get('retry-after')) || 0) * 1000 + 2000 * 2 ** attempt;
    console.log(`    ${res.status}, backing off ${wait}ms`);
    await sleep(wait);
    return getJson(url, init, attempt + 1);
  }
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(String(res.status));
  return res.json();
}

/** Strip the bits of a title that are ours, not the work's: "(Hickman)", "S1-2". */
const clean = (title) =>
  title
    .replace(/\((?:early seasons|hickman|[^)]*\bonly\b[^)]*)\)/gi, '')
    .replace(/\s+\/.*$/, '')
    .replace(/\s+(?:S\d+(?:[-–]\d+)?|Season \d+)$/i, '')
    .trim();

async function anilist(title, type) {
  const query = 'query($s:String,$t:MediaType){Media(search:$s,type:$t){coverImage{large}}}';
  const json = await getJson('https://graphql.anilist.co', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify({ query, variables: { s: title, t: type } }),
  });
  return json?.data?.Media?.coverImage?.large ?? null;
}

async function tvmaze(title) {
  const json = await getJson(`https://api.tvmaze.com/singlesearch/shows?q=${encodeURIComponent(title)}`);
  return json?.image?.original ?? json?.image?.medium ?? null;
}

const WIKI = 'https://en.wikipedia.org/w/api.php?action=query&format=json&prop=pageimages&piprop=thumbnail&pithumbsize=500&pilicense=any&redirects=1';
const SUFFIX = { film: ['film'], game: ['video game'], comic: ['comics', 'comic book', 'comic'] };

/** The lead image of the first page that exists, in the order given. */
async function wikiTitles(titles) {
  const json = await getJson(`${WIKI}&titles=${encodeURIComponent(titles.join('|'))}`);
  const pages = Object.values(json?.query?.pages ?? {});
  const norm = new Map((json?.query?.normalized ?? []).map((n) => [n.from, n.to]));
  const redir = new Map((json?.query?.redirects ?? []).map((r) => [r.from, r.to]));
  for (const t of titles) {
    const name = redir.get(norm.get(t) ?? t) ?? norm.get(t) ?? t;
    const page = pages.find((p) => p.title === name);
    if (page?.thumbnail?.source) return page.thumbnail.source;
  }
  return null;
}

async function wikipedia(title, cat) {
  const variants = [...SUFFIX[cat].map((s) => `${title} (${s})`), title];
  const direct = await wikiTitles(variants);
  if (direct) return direct;
  const search = await getJson(
    `${WIKI}&generator=search&gsrlimit=1&gsrsearch=${encodeURIComponent(`${title} ${SUFFIX[cat][0]}`)}`
  );
  const page = Object.values(search?.query?.pages ?? {})[0];
  return page?.thumbnail?.source ?? null;
}

function lookup(item) {
  let title = clean(item.title);
  // "Shogun (2024)", "Narcos (S1-3)": search APIs want the bare name.
  if (item.cat === 'show' || item.cat === 'anime' || item.cat === 'manga') title = title.replace(/\s*\([^)]*\)/g, '');
  if (item.cat === 'anime') return anilist(title, 'ANIME');
  if (item.cat === 'manga') return anilist(title, 'MANGA');
  if (item.cat === 'show') return tvmaze(title);
  return wikipedia(title, item.cat);
}

function render(map) {
  const rows = Object.entries(map)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, url]) => `  ${JSON.stringify(id)}: ${url === null ? 'null' : JSON.stringify(url)},`)
    .join('\n');
  return `// Poster or cover art for every non-book item, keyed by item id. Generated by
// scripts/fetch-posters.mjs and committed so the app never calls those APIs at
// runtime. Regenerate with \`npm run posters\` after adding items; existing
// entries are left alone. Set an entry to null to keep a wrong match out.

export const posters = {
${rows}
};
`;
}

const todo = media.filter((m) => !(m.id in found));
console.log(`${todo.length} to look up, ${media.length - todo.length} already done`);

let hits = 0;
for (const [i, item] of todo.entries()) {
  try {
    const url = await lookup(item);
    if (url) {
      found[item.id] = url;
      hits++;
    }
    console.log(`${String(i + 1).padStart(3)}/${todo.length} ${url ? 'ok  ' : 'miss'} ${item.cat} ${item.title}`);
  } catch (err) {
    console.log(`${String(i + 1).padStart(3)}/${todo.length} err  ${item.cat} ${item.title}: ${err.message}`);
  }
  if ((i + 1) % 20 === 0) writeFileSync(OUT, render(found));
  await sleep(DELAY[item.cat] ?? 500);
}

writeFileSync(OUT, render(found));
console.log(`done: ${hits} found, ${todo.length - hits} missed`);
